version: '3.8'

services:
  app:
    build: ./app
    container_name: app_container
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=kuzmin_bot
      - DB_USER=bot
      - DB_PASSWORD=TripleSix99
      - TELEGRAM_TOKEN=7083307173:AAFpVbYNc-qbHwfxXFMyxGlWIi6d6G9Oyf8
    command: sh -c "sleep 10 && python bot.py"  # Добавляем задержку
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    build: ./db
    container_name: db_container
    environment:
      POSTGRES_DB: kuzmin_bot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: TripleSix99
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
